### PR TITLE
Text changes

### PR DESCRIPTION
**Pull request by shayr1**
Hi Sergei.

Went over the changes, though only #11 - developer responsibility needed any changes, the rest seems I just translated them like new changes due to languages differences.

### CODE REVIEW

**Comment by sergeicodes** [comment]
Hi @shayr1, could you rebase with the latest changes, it seems that your MR contains some changes which were already merged. Thanks!

**Comment by shayr1** [comment]
Hi.
I have rebased now, hoepfully it's better

**Comment by sergeicodes** [comment]
> Hi. I have rebased now, hoepfully it's better

Could you maybe make a fresh PR? The 8 files you brought in this PR are outdated, I removed some of them time ago.

**Comment by shayr1** [comment]
closing PR and making new one

**Pull request closed without merging**
