### PR TITLE
Adding Arabic Language

### PR DESCRIPTION
**Pull request by MidooDj**
Adding the Arabic translation to the project.

### CODE REVIEW

**Comment by sergeicodes** [comment]
@MidooDj can you check the Deploy Preview if your changes are looking good? For me footer has some issues with words, right?

**Review by MidooDj — COMMENTED** [review]
Update Footer

**Comment by MidooDj** [comment]
> @MidooDj can you check the Deploy Preview if your changes are looking good? For me footer has some issues with words, right?

Hi @sergeicodes  Done. Please check footer again.

**Comment by sergeicodes** [comment]
@MidooDj thanks!

**Pull request merged**
